on : push
jobs : 
    last-job :
          runs-on : windows-latest
          steps :
            - run : node --version
            - uses : actions/checkout@v3
            - run : npm ci
            - run : npx eslint .
            - run : node index.js